name: Build
on:
  push:
  workflow_dispatch:

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - uses: docker/build-push-action@v5
        with:
          push: false
          file: ./Dockerfile